// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3sDIhXPm6LR-0QseE6o4gLAyHt1er6fk',
    appId: '1:565253869773:android:30fda0f1aba40fd2af5984',
    messagingSenderId: '565253869773',
    projectId: 'hidden-gem-c971c',
    storageBucket: 'hidden-gem-c971c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM85rPF7Kvi1SQUArLa8jlJshyoMQoGpU',
    appId: '1:565253869773:ios:582b0e1492a7ce39af5984',
    messagingSenderId: '565253869773',
    projectId: 'hidden-gem-c971c',
    storageBucket: 'hidden-gem-c971c.firebasestorage.app',
    androidClientId:
        '565253869773-5qfjoh6b4vao51246etnp07j3ko3th15.apps.googleusercontent.com',
    iosClientId:
        '565253869773-enhqevdn1r5pn07td2lcqk6ipevvgf3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiddenGem',
  );
}
